version: "3"
services:
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     - MYSQL_DATABASE=tpachato
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
   ports:
      - "3306:3306"
   volumes:
      - db:/var/lib/mysql
   
 app:
   container_name: spring
   image: khalilbnt/devops_project_5ds1group5:latest
   depends_on:
     - mysqldb
   build: .
   restart: on-failure
   ports:
     - "8089:8089"
   environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       "spring.jpa.hibernate.ddl-auto" : "update"}'
   stdin_open: true
   tty: true
 sonarqube:
  image: sonarqube:8.9.7-community
  ports:
   - "9000:9000"
   - "9092:9092"
  volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_data:/opt/sonarqube/data
 nexus:
  image: sonatype/nexus3
  ports:
  - "8081:8081"
  volumes:
   - "nexus-data:/nexus-data"
volumes:
 sonarqube_data: {}
 sonarqube_extensions: {}
 sonarqube_conf: {}
 nexus-data: {}
 db:
 
